<div class="footer-custom-content">
        <div>
                <span>My Account</span>
                <ul>
                    <li><a href="#">My account</a></li>
                    <li><a href="#">Personal Information</a></li>
                    <li><a href="#">Payment methods</a></li>
                    <li><a href="#">Order history</a></li>
                    <li><a href="#">Payment Options</a></li>
                    <li><a href="#">Discount</a></li>
                </ul>
        </div>
        <div>
            <span>Customer Services</span>
            <ul>
                <li><a href="#">Help & Contact</a></li>
                <li><a href="#">Shipping Taxes</a></li>
                <li><a href="#">Payment Methods</a></li>
                <li><a href="#">Return Policy</a></li>
                <li><a href="#">What's New</a></li>
                <li><a href="#">Affiliates</a></li>
            </ul>
        </div>
        <div>
            <span class="contact-span">Contact Details</span>
            <ul class="contact-span-details">
                <li>
                    <div>
                        <span>0203 - 980 - 14 - 79</span><br>
                        <span>0203 - 478 - 12 - 96</span>
                    </div>
                </li>
                <li>
                    <div>
                        <span>vene@gmail.com</span><br>
                        <span>venedor@mail.com</span>
                    </div>
                </li>
                <li>
                    <div>
                        <span>venedor_contact</span><br>
                        <span>venedor_support</span>
                    </div>
                </li>
            </ul>
        </div>
        <div>
            <span>Information</span>
            <ul>
                <li><a href="#">New Products</a></li>
                <li><a href="#">Top Sellers</a></li>
                <li><a href="#">Special Products</a></li>
                <li><a href="#">Manufacturers</a></li>
                <li><a href="#">Suppliers</a></li>
                <li><a href="#">Today's Offers</a></li>
            </ul>
        </div>
        <div>
            <span class="insta-span">Instagram</span>
            <div class="instagram">
                <a href="#"><div></div></a>
                <a href="#"><div></div></a>
                <a href="#"><div></div></a>
                <a href="#"><div></div></a>
                <a href="#"><div></div></a>
                <a href="#"><div></div></a>
            </div>
        </div>
</div>
