<div class="payment-methods">
    <div class="mastercard-div">
        <img src='<?= $this->getViewFileUrl("images/mastercard.png") ?>'>
    </div>
    <div class="paypal-div">
        <img src='<?= $this->getViewFileUrl("images/paypal.png") ?>'>
    </div>
    <div class="amex-div">
        <img src='<?= $this->getViewFileUrl("images/amex.png") ?>'>
    </div>
    <div class="maestro-div">
        <img src='<?= $this->getViewFileUrl("images/maestro.png") ?>'>
    </div>
    <div class="visa-div">
        <img src='<?= $this->getViewFileUrl("images/visa.png") ?>'>
    </div>
</div>
