<?php
/** @var Edit $block */

use Alliance\Linkedin\Block\Linkedin\Edit;

?>

    <legend class="legend"><span><?php echo __('Linkedin Information') ?></span></legend>
    <p>
    <div class="field linkedin_profile" >
        <label for="linkedin_profile" class="label"><span><?php
                echo __('Linkedin Profile Url') ?></span></label>
        <div class="control">
            <input type="url" name="linkedin_profile" id="linkedin_profile" title="<?php echo __('Linkedin') ?>">
        </div>
    </div>
    </p>
